"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class thermal_depth_t(object):
    __slots__ = ["utime", "temperature", "distance_x", "distance_y"]

    __typenames__ = ["int64_t", "float", "float", "float"]

    __dimensions__ = [None, [768], [768], [768]]

    def __init__(self):
        self.utime = 0
        self.temperature = [ 0.0 for dim0 in range(768) ]
        self.distance_x = [ 0.0 for dim0 in range(768) ]
        self.distance_y = [ 0.0 for dim0 in range(768) ]

    def encode(self):
        buf = BytesIO()
        buf.write(thermal_depth_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>768f', *self.temperature[:768]))
        buf.write(struct.pack('>768f', *self.distance_x[:768]))
        buf.write(struct.pack('>768f', *self.distance_y[:768]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != thermal_depth_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return thermal_depth_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = thermal_depth_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.temperature = struct.unpack('>768f', buf.read(3072))
        self.distance_x = struct.unpack('>768f', buf.read(3072))
        self.distance_y = struct.unpack('>768f', buf.read(3072))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if thermal_depth_t in parents: return 0
        tmphash = (0xe0ca7b114ff8c032) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if thermal_depth_t._packed_fingerprint is None:
            thermal_depth_t._packed_fingerprint = struct.pack(">Q", thermal_depth_t._get_hash_recursive([]))
        return thermal_depth_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", thermal_depth_t._get_packed_fingerprint())[0]

